data:
  batch_size: 256
  cache_size: 4000
  augment: 1.0
  noise: 0.5
  patched: true
  patch_size: 80
  patch_pad: 8
  val_batch_size: 5
  train_datasets:
  - all
  train_folder: /dsk1/danil/3d/nerf/data/games/images/
  val_folder:
  - /dsk1/danil/3d/nerf/data/facebook/
  mode: bilinear
  out: /dsk1/danil/3d/nerf/results
metrics:
  loss_coeff:
    mae: 0.0
    mse: 1.0
    psnr: 0.0
    ssim: 0.0
    rbf: 0.0
  loss_name:
  - mse
  - mae
model:
  block_size: 2
  in_channels: 1
  dropout: 0.0
  out_channels:
  final_act: Tanh
  first_block_type: none
  kernel_size: 3
  main_block_type: squeeze
  n_blocks: 4
  n_channels: 72
  name: squeeze-model
  upscale_factor: 2
  upscaling_method: ConvTranspose
  use_norm: false
  avg:
  - ema
  - swa
saving:
  ckp_folder: checkpoints/
  log_folder: logs/
train:
  base_rate: 0.004
  rbf_filters:
  epochs: 30
  steps: 2000
  log_freq: 50
  optimizer: lamb
  max_grad_norm: 0.1
  pretrained_weights: ''
  hard_rate: 0.25
  hard_prob: 0.5
  hard_alpha: 0.95
  hard_warmup: 5
  sched: 'cosine'
  sched_min: 0.005
  sched_initial: 0.25
  sched_start: 2
  sched_mult: 2
  sched_gamma: 0.4
  sched_steps:
  - 7
  - 17
  - 30
  - 45
  - 75
  - 90
  - 125
  - 150
  - 175
  - 200
  - 225
