data:
  batch_size: 256
  cache_size:
  augment: 0.0
  noise: 0.0
  patched: true
  patch_size: 80
  patch_pad: 8
  val_batch_size: 5
  train_datasets:
  - all
  train_folder: /dsk1/danil/3d/nerf/data/games/julia/
  val_folder:
  - /dsk1/danil/3d/nerf/data/facebook/
  mode: bilinear
  out: /dsk1/danil/3d/nerf/results
metrics:
  loss_coeff:
    mae: 0.0
    mse: 1.0
    psnr: 0.0
    ssim: 0.0
    rbf: 0.0
  loss_name:
  - mse
  - mae
model:
  block_size: 2
  in_channels: 1
  out_channels: 3
  dropout: 0.0
  final_act: Tanh
  first_block_type: none
  kernel_size: 3
  main_block_type: mini
  n_blocks: 4
  n_channels: 6
  name: mini-model
  upscale_factor: 2
  upscaling_method: ConvTranspose
  use_norm: false
saving:
  ckp_folder: checkpoints/
  log_folder: logs/
train:
  base_rate: 0.005
  rbf_filters:
  epochs: 30
  steps: 2000
  log_freq: 50
  optimizer: adam
  pretrained_weights: ''
  sched: 'one'
  sched_min: 0.01
  sched_initial: 0.25
  sched_start: 3
  sched_mult: 1
  sched_gamma: 0.4
  sched_steps:
  - 7
  - 17
  - 30
  - 45
  - 75
  - 90
  - 125
  - 150
  - 175
  - 200
  - 225
