data:
  batch_size: 256
  cache_size: 4000
  augment: 0.0
  noise: 0.0
  patched: true
  val_patched: false
  patch_size: 84
  patch_pad: 6
  val_batch_size: 1
  height:
  width:
  train_datasets:
  - all
  train_folder: /dsk1/danil/3d/nerf/data/games/images/
  val_folder:
  - /dsk1/danil/3d/nerf/data/games/test/facebook/
  - /dsk1/danil/3d/nerf/data/games/test/ui/
  - /dsk1/danil/3d/nerf/data/games/test/unreal-engine/
  - /dsk1/danil/3d/nerf/data/games/test/unsplash2k/
  mode: bilinear
  out: /dsk1/danil/3d/nerf/results
loss:
  threshold: 0.001
  weights:
    mae: 1.0
    mse: 0.0
    psnr: 0.0
    ssim: 0.0
    rbf: 0.0
    disc: 0.0
  name:
  - mse
  - mae
model:
  block_size: 1
  in_channels: 1
  dropout: 0.0
  out_channels: 12
  final_act: Tanh
  first_block_type: none
  kernel_size: 1
  main_block_type: reduce
  n_blocks: 3
  n_channels: 12
  name: reduce
  upscale_factor: 2
  upscaling_method: PixelShuffle
  use_norm: false
  skip_normalize: False
  enhance: false
  avg: []
saving:
  ckp_folder: checkpoints/
  log_folder: logs/
train:
  base_rate: 0.005
  rbf_filters:
  epochs: 63
  steps: 2000
  acc_grads: 1
  log_freq: 50
  optimizer: lamb
  max_grad_norm: 0.1
  pretrained_weights: ''
  hard:
    rate: 0.1
    prob: 0.5
    alpha: 0.95
    warmup: 5
  disc:
    lr: 0.001
    warmup: 10
    dim: 32
    blocks: 2
    freq: 1
  sched:
    name: 'cosine'
    min: 0.01
    initial: 0.25
    cycles: 6
    start: 1
    mult: 2
    gamma: 0.4
    steps:
    - 7
    - 17
    - 30
    - 45
    - 75
    - 90
    - 125
    - 150
    - 175
    - 200
    - 225
