data:
  batch_size: 256
  augment: false
  patched: true
  patch_size: 80
  patch_pad: 8
  val_batch_size: 2
  train_datasets:
  - all
  train_folder: /dsk1/danil/3d/nerf/data/games/julia/
  val_folder:
  - /dsk1/danil/3d/nerf/data/facebook/
  mode: bilinear
  out: /dsk1/danil/3d/nerf/results
metrics:
  loss_coeff:
    mae: 0.0
    mse: 1.0
    psnr: 0.0
    ssim: 0.0
    rbf: 0.01
  loss_name:
  - mse
  - mae
model:
  block_size: 2
  channels: 1
  final_act: Tanh
  first_block_type: none
  kernel_size: 3
  main_block_type: wide
  n_blocks: 1
  n_channels: 96
  name: wm-patched
  upscale_factor: 2
  upscaling_method: ConvTranspose
saving:
  ckp_folder: checkpoints/
  log_folder: logs/
train:
  base_rate: 0.002
  rbf_filters: 48
  n_epochs: 50
  steps: 10000
  log_freq: 50
  optimizer: adam
  pretrained_weights: ''
  sched: 'cosine'
  sched_min: 0.01
  sched_first: 5
  sched_mult: 1
  sched_gamma: 0.4
  sched_steps:
  - 7
  - 17
  - 30
  - 45
  - 75
  - 90
  - 125
  - 150
  - 175
  - 200
  - 225
